import { StyleSheet } from "react-native";

import { colors, radii, spacing, typography } from "../../theme/tokens";

const palette = colors.dark;
export const discoveryStyles = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: spacing.screen,
    paddingBottom: spacing.hero,
    gap: spacing.lg,
  },
  pageHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginTop: spacing.sm,
    marginBottom: spacing.lg,
    gap: spacing.md,
  },
  pageHeaderText: {
    flex: 1,
  },
  pageTitle: {
    color: palette.onSurface,
    marginBottom: spacing.xs,
    ...typography.displaySmall,
  },
  pageSubtitle: {
    color: palette.onSurfaceSoft,
    ...typography.bodyMedium,
  },
  pageHeaderButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.outline,
    alignItems: "center",
    justifyContent: "center",
  },
  headerBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: palette.secondary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  headerBadgeText: {
    color: palette.onSecondary,
    ...typography.labelSmall,
  },
  primaryButton: {
    backgroundColor: palette.primary,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonCompact: {
    minHeight: 40,
    paddingHorizontal: spacing.sm,
  },
  primaryButtonText: {
    color: palette.onPrimary,
    ...typography.labelLarge,
  },
  secondaryButton: {
    borderRadius: radii.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.outlineStrong,
    backgroundColor: palette.surfaceVariant,
  },
  secondaryButtonCompact: {
    minHeight: 40,
    paddingHorizontal: spacing.sm,
  },
  secondaryButtonText: {
    color: palette.onSurface,
    ...typography.labelLarge,
  },
  discoveryTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  discoveryTitleWrap: {
    flex: 1,
  },
  discoveryEyebrow: {
    color: palette.onSurfaceVariant,
    marginBottom: spacing.xs,
    ...typography.labelLarge,
  },
  discoveryHeading: {
    color: palette.onSurface,
    ...typography.displaySmall,
  },
  discoveryActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.outline,
    alignItems: "center",
    justifyContent: "center",
  },
  discoverySearchBar: {
    minHeight: 62,
    borderRadius: radii.xxl,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.outline,
    paddingLeft: spacing.md,
    paddingRight: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  discoverySearchPrompt: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  discoverySearchText: {
    color: palette.onSurfaceVariant,
    ...typography.titleMedium,
  },
  discoverySearchButton: {
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: palette.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  discoveryHorizontalScroller: {
    marginLeft: -spacing.screen,
    marginRight: -spacing.screen,
  },
  discoveryCategoryRow: {
    gap: spacing.sm,
    paddingLeft: spacing.screen,
    paddingRight: spacing.screen,
  },
  discoveryCategoryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radii.round,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.outline,
  },
  discoveryCategoryChipSelected: {
    backgroundColor: "#F4F4F4",
    borderColor: "#F4F4F4",
  },
  discoveryCategoryLabel: {
    color: palette.onSurfaceVariant,
    ...typography.labelLarge,
  },
  discoveryCategoryLabelSelected: {
    color: "#111111",
  },
  discoverySpotlightCard: {
    backgroundColor: "#121519",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: radii.xxl,
    padding: spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  discoverySpotlightCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  discoverySpotlightTitle: {
    color: palette.onSurface,
    ...typography.headlineSmall,
  },
  discoverySpotlightText: {
    color: palette.onSurfaceSoft,
    ...typography.bodySmall,
  },
  discoverySection: {
    gap: spacing.md,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: palette.onSurface,
    ...typography.headlineSmall,
  },
  sectionMeta: {
    color: palette.onSurfaceVariant,
    ...typography.labelMedium,
  },
  discoverySectionTitleWrap: {
    flex: 1,
    gap: 2,
  },
  discoverySectionSubtitle: {
    color: palette.onSurfaceVariant,
    ...typography.bodySmall,
  },
  discoverySectionLink: {
    color: palette.primary,
    ...typography.labelLarge,
  },
  discoveryRail: {
    gap: spacing.sm,
    paddingLeft: spacing.screen,
    paddingRight: spacing.screen,
  },
  discoveryVehicleCard: {
    width: 152,
    backgroundColor: "transparent",
  },
  discoveryVehicleMedia: {
    height: 108,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.outline,
    marginBottom: 8,
  },
  discoveryVehicleImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#111418",
  },
  discoveryVehicleFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  discoveryFavoriteButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(17,17,17,0.38)",
    alignItems: "center",
    justifyContent: "center",
  },
  discoveryVehicleBody: {
    gap: 1,
  },
  discoveryVehicleTitle: {
    color: palette.onSurface,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  discoveryVehicleMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 1,
    marginBottom: 6,
  },
  discoveryVehicleMeta: {
    color: palette.onSurfaceVariant,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
  },
  discoveryVehiclePriceStack: {
    gap: 0,
  },
  discoveryVehiclePrice: {
    color: palette.onSurface,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  helperText: {
    color: palette.onSurfaceVariant,
    ...typography.bodySmall,
  },
  errorText: {
    color: palette.error,
    ...typography.bodySmall,
  },
  infoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: palette.outline,
    backgroundColor: palette.surface,
  },
  infoCardTextWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  infoCardText: {
    flex: 1,
    color: palette.onSurfaceSoft,
    ...typography.bodySmall,
  },
  infoCardLink: {
    color: palette.primary,
    ...typography.labelLarge,
  },
  searchShell: {
    minHeight: 56,
    borderRadius: radii.lg,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.outline,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
  },
  searchIcon: {
    marginRight: spacing.sm,
  },
  searchInput: {
    flex: 1,
    color: palette.onSurface,
    ...typography.bodyMedium,
  },
  filterSection: {
    gap: spacing.xs,
  },
  filterSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  filterSectionTitle: {
    color: palette.onSurface,
    ...typography.labelLarge,
  },
  filterSectionMeta: {
    color: palette.onSurfaceVariant,
    ...typography.bodySmall,
  },
  filterScroller: {
    marginHorizontal: -spacing.md,
  },
  filterScrollerContent: {
    paddingHorizontal: spacing.md,
    gap: spacing.xs,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  filterChip: {
    backgroundColor: palette.surfaceVariant,
    borderRadius: radii.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderWidth: 1,
    borderColor: palette.outline,
  },
  filterChipSelected: {
    backgroundColor: "rgba(33,216,160,0.14)",
    borderColor: "rgba(33,216,160,0.42)",
  },
  filterChipText: {
    color: palette.onSurfaceSoft,
    ...typography.labelMedium,
  },
  filterChipTextSelected: {
    color: palette.primary,
  },
  filterResetButton: {
    alignSelf: "flex-start",
  },
  filterResetText: {
    color: palette.primary,
    ...typography.labelLarge,
  },
  availabilityCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: palette.outline,
    backgroundColor: palette.surface,
    padding: spacing.md,
    gap: spacing.md,
  },
  availabilityHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  availabilityTitleWrap: {
    flex: 1,
    gap: 4,
  },
  availabilityTitle: {
    color: palette.onSurface,
    ...typography.titleMedium,
  },
  availabilityText: {
    color: palette.onSurfaceVariant,
    ...typography.bodySmall,
  },
  availabilityDateGrid: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  availabilityDateField: {
    flex: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: palette.outline,
    backgroundColor: palette.surfaceVariant,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 4,
  },
  availabilityDateFieldActive: {
    borderColor: "rgba(33,216,160,0.45)",
  },
  availabilityDateLabel: {
    color: palette.onSurfaceVariant,
    ...typography.labelSmall,
  },
  availabilityDateValue: {
    color: palette.onSurface,
    ...typography.bodyMedium,
  },
  availabilitySummary: {
    color: palette.onSurfaceSoft,
    ...typography.bodySmall,
  },
  availabilityPickerWrap: {
    borderRadius: radii.xl,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.outline,
    backgroundColor: palette.surfaceVariant,
  },
  toggleShell: {
    alignSelf: "flex-start",
    flexDirection: "row",
    backgroundColor: palette.surfaceVariant,
    borderRadius: radii.round,
    padding: 4,
    gap: 4,
  },
  toggleButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radii.round,
  },
  toggleButtonSelected: {
    backgroundColor: palette.primary,
  },
  toggleButtonText: {
    color: palette.onSurfaceVariant,
    ...typography.labelLarge,
  },
  toggleButtonTextSelected: {
    color: palette.onPrimary,
  },
  mapPreviewCard: {
    borderRadius: radii.xxl,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.outline,
    padding: spacing.lg,
  },
  mapPreviewTitle: {
    color: palette.onSurface,
    ...typography.headlineSmall,
  },
  mapPreviewSubtitle: {
    color: palette.onSurfaceSoft,
    marginTop: spacing.xs,
    marginBottom: spacing.md,
    ...typography.bodySmall,
  },
  mapCanvas: {
    height: 248,
    position: "relative",
    overflow: "hidden",
    borderRadius: radii.xl,
    backgroundColor: "#0E1218",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    marginBottom: spacing.md,
  },
  mapIslandViewport: {
    flex: 1,
    marginHorizontal: spacing.sm,
    marginVertical: spacing.sm,
    overflow: "hidden",
    borderRadius: radii.xl,
    position: "relative",
  },
  mapIslandSvg: {
    width: "100%",
    height: "100%",
  },
  mapBackdropGlowA: {
    position: "absolute",
    width: 160,
    height: 160,
    borderRadius: 80,
    top: -34,
    left: -18,
    backgroundColor: "rgba(33,216,160,0.1)",
  },
  mapBackdropGlowB: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    bottom: -72,
    right: -24,
    backgroundColor: "rgba(94,161,255,0.12)",
  },
  mapMarkerTapTarget: {
    position: "absolute",
    width: 48,
    height: 48,
    marginLeft: -24,
    marginTop: -24,
    borderRadius: 24,
  },
  mapLegendInline: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.xs,
    marginBottom: spacing.md,
  },
  mapLegendChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: radii.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  mapLegendChipText: {
    color: palette.onSurfaceSoft,
    ...typography.labelSmall,
  },
  mapLegendMetaInline: {
    color: palette.onSurfaceVariant,
    flexShrink: 1,
    ...typography.bodySmall,
  },
  mapAreaScroller: {
    marginBottom: spacing.md,
  },
  mapAreaChipRow: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  mapAreaChip: {
    borderRadius: radii.round,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: palette.surfaceVariant,
    borderWidth: 1,
    borderColor: palette.outline,
  },
  mapAreaChipSelected: {
    backgroundColor: "rgba(33,216,160,0.14)",
    borderColor: "rgba(33,216,160,0.4)",
  },
  mapAreaChipText: {
    color: palette.onSurfaceSoft,
    ...typography.labelMedium,
  },
  mapAreaChipTextSelected: {
    color: palette.primary,
  },
  mapSummaryCard: {
    borderRadius: radii.lg,
    padding: spacing.md,
    backgroundColor: "rgba(255,255,255,0.02)",
    borderWidth: 1,
    borderColor: palette.outline,
    marginBottom: spacing.md,
  },
  mapSummaryTitle: {
    color: palette.onSurface,
    ...typography.titleMedium,
  },
  mapSummaryText: {
    color: palette.onSurfaceVariant,
    marginTop: spacing.xs,
    ...typography.bodySmall,
  },
  resultCard: {
    backgroundColor: palette.surface,
    borderRadius: radii.xxl,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 22,
    elevation: 8,
  },
  resultContentPressable: {
    backgroundColor: "#131519",
  },
  resultMediaShell: {
    height: 194,
    position: "relative",
    overflow: "hidden",
    backgroundColor: palette.surfaceVariant,
  },
  resultCardAccent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  resultImage: {
    width: "100%",
    height: "100%",
    backgroundColor: palette.surfaceVariant,
  },
  resultCardBody: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
  },
  resultEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  resultEyebrowText: {
    color: palette.onSurfaceVariant,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    ...typography.labelSmall,
  },
  resultEyebrowDot: {
    color: palette.onSurfaceVariant,
    ...typography.labelSmall,
  },
  resultHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  resultTitleWrap: {
    flex: 1,
  },
  resultPriceWrap: {
    alignItems: "flex-end",
    paddingLeft: spacing.sm,
  },
  resultTitle: {
    color: palette.onSurface,
    ...typography.titleLarge,
  },
  resultSubtitle: {
    color: palette.onSurfaceVariant,
    marginTop: spacing.xs,
    ...typography.bodySmall,
  },
  resultSpecPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  resultPrice: {
    color: palette.primary,
    ...typography.titleMedium,
  },
  resultPriceLabel: {
    color: palette.onSurfaceVariant,
    ...typography.bodySmall,
  },
  resultSpecPill: {
    borderRadius: radii.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  resultSpecPillText: {
    color: palette.onSurfaceSoft,
    ...typography.labelMedium,
  },
  resultMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  resultHostBlock: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  resultHostAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(33,216,160,0.14)",
    borderWidth: 1,
    borderColor: "rgba(33,216,160,0.2)",
  },
  resultHostAvatarText: {
    color: palette.primary,
    ...typography.titleMedium,
  },
  resultHostCopy: {
    flex: 1,
  },
  resultHostLabel: {
    color: palette.onSurfaceVariant,
    ...typography.labelSmall,
  },
  resultHostName: {
    color: palette.onSurface,
    marginTop: 2,
    ...typography.bodyMedium,
  },
  resultActionsRow: {
    flexDirection: "row",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  statusChip: {
    borderRadius: radii.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  statusChipText: {
    ...typography.labelLarge,
  },
});
